detectors:
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: false
  TooManyStatements:
    enabled: false
  UtilityFunction:
    exclude:
      - Binance::Connector::Api#options_unsigned
